title: Steven Oliver's Blog
email: oliver.steven@gmail.com
description: >-
  Steven Oliver's blog. Musings about software engineering, engineering, and
  anything else of interest.
baseurl: ""
url: ""
github_username:  steveno
linkedin_username: stevenoliver
timezone: America/New_York

# Build settings
theme: minima
plugins:
  - jekyll-feed
highlighter: pygments
markdown: redcarpet

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - README.md
  - new_draft.sh
  - new_post.sh
  - start_demo.sh
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - .sass-cache/
  - vendor
