title: Steven Oliver
author:
  name: Steven Oliver
  email: oliver.steven@gmail.com
description: >-
  I write about software engineering and anything else of interest.
url: https://steveno.github.io
timezone: America/New_York
show_excerpts: true
excerpt_separator: <!--more-->
source-code: https://github.com/steveno/steveno.github.io

# Social links
github_username: steveno
linkedin_username: stevenoliver
mastodon:
  - username: steveno
    instance: mastodon.social

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  partof:
    output: true

# Exclude the following from processing
exclude:
  - README.md
  - ja
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - .sass-cache/
  - vendor
