title: Steven Oliver
email: oliver.steven@gmail.com
description: >-
  Steven Oliver's homepage. I write about software engineering, engineering, and
  anything else of interest.
baseurl: ""
url: ""
timezone: America/New_York
show_excerpts: true
excerpt_separator: <!--more-->

# Social links
github_username:  steveno
linkedin_username: stevenoliver
mastodon:
  - username: steveno
    instance: mastodon.social

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude the following from processing
exclude:
  - README.md
  - ja
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - .sass-cache/
  - vendor
