title: Steven Oliver's Blog
email: oliver.steven@gmail.com
description: >-
  Steven Oliver's blog. Musings about software engineering, engineering, and
  anything else of interest.
baseurl: ""
url: ""
github_username:  steveno
linkedin_username: stevenoliver
timezone: America/New_York

# Build settings
theme: minima
highlighter: pygments
markdown: redcarpet
plugins:
  - jekyll-feed

mastodon:
  instance: mastodon.social
  username: steveno

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - README.md
  - ja
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - .sass-cache/
  - vendor
